### PR TITLE
fix: cvflatbutton active color does not change in dialog

### LINKED ISSUE #233: CVFlatButton active color does not change in dialog
**Describe the bug**
The button state does not change from inactive to active when the text field has text.

**To Reproduce**

1. Go to any Owned Group
2. Click on 'Add' on the right of Mentors/Members
3. Edit the email text field
4. See the error

**Expected behavior**
The flat button color should be green when the text field is not empty.

**Screenshots

https://user-images.githubusercontent.com/77198905/178121337-5d8e9d43-b2f6-4e81-8623-ffb80f33e9f4.mp4

**Are you working on this issue? (Yes/No)**

### PR DESCRIPTION
**Pull request by Aditya-150**
Fixes #233 

Describe the changes you have made in this PR -
There was a bug in **package:mobile_app/ui/components/cv_flat_button.dart** .
The **foregroundColor** was set to grey by default.  That's why the color of the button was not changing on state change.

Screenshots of the changes (If any) -

https://user-images.githubusercontent.com/78409764/188433775-eb043b0b-a228-4ce7-b971-16cc1dc84d3c.mp4

Note: Please check Allow edits from maintainers. if you would like us to assist in the PR.

### CODE REVIEW

**Comment by aman-singh7** [comment]
@Aditya-150 Run the command "flutter format ." in the project's home directory. And commit the changes.

**Comment by Aditya-150** [comment]
> @Aditya-150 Run the command "flutter format ." in the project's home directory. And commit the changes.

Thanks @aman-singh7  for pointing out that. I just forgot to format the file.

**Comment by Aditya-150** [comment]
Hey, @aman-singh7 sorry for disturbing for you. But can you review it.. #240 #233

**Comment by aman-singh7** [comment]
Thank you for your contributions @Aditya-150, Initial impressions of the code looks good. I will review and test it very soon.

**Review by aman-singh7 — APPROVED** [review]

**Pull request merged**
