### PR TITLE
Updated screenshots of mobile app

### PR DESCRIPTION
**Pull request by suyash-patil**

### CODE REVIEW

**Review by manjotsidhu — APPROVED** [review]
@suyash-patil can you also update the screenshots in README.md ? Those screenshots are really old and dark mode screenshots also has to be included.

**Comment by suyash-patil** [comment]
@manjotsidhu should I replace all the screenshots or just update the changed.

**Comment by manjotsidhu** [comment]
You can replace them with new ones

**Comment by suyash-patil** [comment]
@manjotsidhu I have made the changes.

**Review by manjotsidhu — APPROVED** [review]
LGTM! CC: @Nitish145

**Review by manjotsidhu — APPROVED** [review]

**Pull request merged**
