### PR TITLE
feat(profile): implement update profile picture

### LINKED ISSUE #222: Upload profile picture in app
The updating profile picture is currently not available in the app.

**Are you working on this? (Yes/No)**
Yes

### PR DESCRIPTION
**Pull request by aman-singh7**
Fixes #222 

Describe the changes you have made in this PR -

Screenshots of the changes (If any) -

Note: Please check Allow edits from maintainers. if you would like us to assist in the PR.

### CODE REVIEW

**Comment by manjotsidhu** [comment]
@aman-singh7 It's very important for us to keep minimal number third party packages as much as possible, so keep that in mind while implementing new features.

**Comment by aman-singh7** [comment]
> @aman-singh7 It's very important for us to keep minimal number third party packages as much as possible, so keep that in mind while implementing new features.

Yup, I have added only two dependencies. One is to pick the image and another one to crop that picked one.

**Comment by manjotsidhu** [comment]
@aman-singh7 Can you also send screenshot/screen recording here to see how the update UI and UX looking like ?

**Comment by aman-singh7** [comment]
> @aman-singh7 Can you also send screenshot/screen recording here to see how the update UI and UX looking like ?

Screenshots are mentioned in my [biweekly blog](https://medium.com/@aman_s07/biweekly-report-1-gsoc-2022-39ca8f408f37).
And here is the screen recording of the flow:

https://user-images.githubusercontent.com/77198905/176388175-e240f6b7-75d5-4ea2-90d5-a399a452c99a.mp4

**Review by manjotsidhu — APPROVED** [review]

**Pull request merged**
