### PR TITLE
feat: added flutter-lints package 

### LINKED ISSUE #136: Flutter 2.5: Migrate to recommended `flutter_lints` package
## What is `flutter_lints` ?

The package:flutter_lints defines the latest set of recommended lints that encourage good coding practices for Flutter apps, packages, and plugins. Projects created with flutter create using Flutter version 2.3.0-12.0.pre or newer are already enabled to use the latest set of recommended lints. Projects created prior to that version can upgrade to it with the instructions in this guide.
https://flutter.dev/docs/release/breaking-changes/flutter-lints-package

## TL;DR

Flutter 2.5 introduced it's own package `flutter_lints` and is recommended now to use since 2.5.
Migration Guide: https://flutter.dev/docs/release/breaking-changes/flutter-lints-package#migration-guide

### PR DESCRIPTION
**Pull request by Neha62-lit**
Fixes #136 

Describe the changes you have made in this PR -
1. Added all proper linter rules.
2. Migrated flutter-lints package.

Screenshots of the changes (If any) -

This screenshot shows that "No issues found" i.e there is no warnings/errors in the code.

Screenshot (160)

### CODE REVIEW

**Comment by Neha62-lit** [comment]
Hey @manjotsidhu, Please review and merge PR.

**Review by manjotsidhu — APPROVED** [review]
Good work 👍

**Comment by manjotsidhu** [comment]
@Neha62-lit could make a new Issue with the checklist of all the issues that are disabled ? It would be easy for us to track later.

**Comment by Neha62-lit** [comment]
> @Neha62-lit could you make a new Issue with the checklist of all the issues that are disabled ? It would be easy for us to track later. I will merge this PR once the CI checks are successful.

Can you explain me, What I have to do here?

**Comment by manjotsidhu** [comment]
> > @Neha62-lit could you make a new Issue with the checklist of all the issues that are disabled ? It would be easy for us to track later. I will merge this PR once the CI checks are successful.
> 
> Can you explain me, What I have to do here?

You have to create a new issue for fixing flutter_lints rules and in that issue we can manage the checklist of the rules which are to fixed.

**Comment by Neha62-lit** [comment]
> > > @Neha62-lit could you make a new Issue with the checklist of all the issues that are disabled ? It would be easy for us to track later. I will merge this PR once the CI checks are successful.
> > 
> > 
> > Can you explain me, What I have to do here?
> 
> You have to create a new issue for fixing flutter_lints rules and in that issue we can manage the checklist of the rules which are to fixed.

Okay, will do that.

**Pull request merged**
