### PR TITLE
Updated deprecated features leading to CI Failure

### LINKED ISSUE #135: CI Failing due to usage of some deprecated features
**Describe the bug**
CI fails after #84 due to the following features ( `accentColor`, `accentTextTheme` and `brightness` )
These errors are thrown by `flutter analyze` and the log of it is attached below :

<details>
<summary>CI Flutter analyze log</summary>

```
Analyzing mobile-app...                                         

   info • 'accentColor' is deprecated and shouldn't be used. Use colorScheme.secondary instead. For more information, consult the migration guide at https://flutter.dev/docs/release/breaking-changes/theme-data-accent-properties#migration-guide. This feature was deprecated after v2.3.0-0.1.pre. • lib/cv_theme.dart:56:9 • deprecated_member_use
   info • 'accentColor' is deprecated and shouldn't be used. No longer used by the framework, please remove any reference to it. For more information, consult the migration guide at https://flutter.dev/docs/release/breaking-changes/theme-data-accent-properties#migration-guide. This feature was deprecated after v2.3.0-0.1.pre. • lib/ib_theme.dart:11:7 • deprecated_member_use
   info • 'accentTextTheme' is deprecated and shouldn't be used. No longer used by the framework, please remove any reference to it. For more information, consult the migration guide at https://flutter.dev/docs/release/breaking-changes/theme-data-accent-properties#migration-guide. This feature was deprecated after v2.3.0-0.1.pre. • lib/ib_theme.dart:21:7 • deprecated_member_use
   info • 'accentTextTheme' is deprecated and shouldn't be used. No longer used by the framework, please remove any reference to it. For more information, consult the migration guide at https://flutter.dev/docs/release/breaking-changes/theme-data-accent-properties#migration-guide. This feature was deprecated after v2.3.0-0.1.pre. • lib/ib_theme.dart:21:42 • deprecated_member_use
   info • 'accentColor' is deprecated and shouldn't be used. Use colorScheme.secondary instead. For more information, consult the migration guide at https://flutter.dev/docs/release/breaking-changes/theme-data-accent-properties#migration-guide. This feature was deprecated after v2.3.0-0.1.pre. • lib/main.dart:43:15 • deprecated_member_use
   info • 'accentColor' is deprecated and shouldn't be used. Use colorScheme.secondary instead. For more information, consult the migration guide at https://flutter.dev/docs/release/breaking-changes/theme-data-accent-properties#migration-guide. This feature was deprecated after v2.3.0-0.1.pre. • lib/main.dart:55:15 • deprecated_member_use
   info • 'brightness' is deprecated and shouldn't be used. This property is no longer used, please use systemOverlayStyle instead. This feature was deprecated after v2.4.0-0.0.pre. • lib/ui/views/ib/ib_landing_view.dart:71:7 • deprecated_member_use

7 issues found. (ran in 20.7s)
```
</details>

Checklist :
- [ ] `accentColor` depreciated, replace it with `colorScheme.secondary`
- [ ] `accentTextTheme` depreciated, replace it with `colorScheme.secondary`
- [ ] `brightness` depreciated, replace it with `ThemeData.estimateBrightnessForColor()`

More info: https://flutter.dev/docs/release/breaking-changes/theme-data-accent-properties#accentcolorbrightness
Welcome to Flutter 2.5 💯 

_edited by @manjotsidhu_

### PR DESCRIPTION
**Pull request by roopak99**
Fixes #135 

Describe the changes you have made in this PR - Updated the deprecated features according to the documentation

Screenshots of the changes (If any) -

Note: Please check Allow edits from maintainers. if you would like us to assist in the PR.

### CODE REVIEW

**Comment by roopak99** [comment]
I have upgraded my flutter to 2.5 recently . I have no idea why the `pubspec.lock` has so many changes.

**Comment by roopak99** [comment]
I am really sorry , the CI is still failing . I will take a deeper look into this issue and try to resolve it

**Comment by manjotsidhu** [comment]
> I am really sorry , the CI is still failing . I will take a deeper look into this issue and try to resolve it

You should do `flutter upgrde` once and then `flutter packages get`, it will modify your pubspec.lock and then push those changes.

**Comment by manjotsidhu** [comment]
superseded by #144

**Pull request closed without merging**
