### PR TITLE
Fixed sort_constructors_first

### PR DESCRIPTION
**Pull request by M-A-D-A-R-A**
Refer #149 

Fixed:
 - sort_constructors_first

### CODE REVIEW

**Comment by manjotsidhu** [comment]
@M-A-D-A-R-A Please explain your changes done in this PR along with how it fixes the rule `sort_constructors_first`.

**Comment by M-A-D-A-R-A** [comment]
> @M-A-D-A-R-A Please explain your changes done in this PR along with how it fixes the rule (`sort_constructors_first`). Also I don't see this rule being enabled or removed from https://github.com/CircuitVerse/mobile-app/blob/master/analysis_options.yaml#L9

I refered to [this](https://dart-lang.github.io/linter/lints/sort_constructors_first.html).

So for eg :- 
Before it was
```
class CollaboratorAttributes {
    CollaboratorAttributes({
    this.name,
  });

String name;
```

and Now 

```
class CollaboratorAttributes {
  String name;
  CollaboratorAttributes({
    this.name,
  });
```

Im new to this so i dont know i did the right thing or not.

**Comment by manjotsidhu** [comment]
> > @M-A-D-A-R-A Please explain your changes done in this PR along with how it fixes the rule (`sort_constructors_first`). Also I don't see this rule being enabled or removed from https://github.com/CircuitVerse/mobile-app/blob/master/analysis_options.yaml#L9
> 
> I refered to [this](https://dart-lang.github.io/linter/lints/sort_constructors_first.html).
> 
> So for eg :- Before it was
> 
> ```
> class CollaboratorAttributes {
>     CollaboratorAttributes({
>     this.name,
>   });
> 
> String name;
> ```
> 
> and Now
> 
> ```
> class CollaboratorAttributes {
>   String name;
>   CollaboratorAttributes({
>     this.name,
>   });
> ```
> 
> Im new to this so i dont know i did the right thing or not.
> 
> and yeah it was mentioned in those 26 issue so i started working on this without asking I didn't knew it was disabled.

Remove the rule from `analysis_options.yaml`.

This https://dart-lang.github.io/linter/lints/sort_constructors_first.html says GOOD as constructor being ordered at first and BAD if constructor is not in first. Your change does exactly the opposite.

**Comment by M-A-D-A-R-A** [comment]
> > > @M-A-D-A-R-A Please explain your changes done in this PR along with how it fixes the rule (`sort_constructors_first`). Also I don't see this rule being enabled or removed from https://github.com/CircuitVerse/mobile-app/blob/master/analysis_options.yaml#L9
> > 
> > 
> > I refered to [this](https://dart-lang.github.io/linter/lints/sort_constructors_first.html).
> > So for eg :- Before it was
> > ```
> > class CollaboratorAttributes {
> >     CollaboratorAttributes({
> >     this.name,
> >   });
> > 
> > String name;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and Now
> > ```
> > class CollaboratorAttributes {
> >   String name;
> >   CollaboratorAttributes({
> >     this.name,
> >   });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Im new to this so i dont know i did the right thing or not.
> > and yeah it was mentioned in those 26 issue so i started working on this without asking I didn't knew it was disabled.
> 
> Remove the rule from `analysis_options.yaml`.
> 
> This https://dart-lang.github.io/linter/lints/sort_constructors_first.html says GOOD as constructor being ordered at first and BAD if constructor is not in first. Your change does exactly the opposite.

So should i close this PR ?

**Comment by manjotsidhu** [comment]
> > > > @M-A-D-A-R-A Please explain your changes done in this PR along with how it fixes the rule (`sort_constructors_first`). Also I don't see this rule being enabled or removed from https://github.com/CircuitVerse/mobile-app/blob/master/analysis_options.yaml#L9
> > > 
> > > 
> > > I refered to [this](https://dart-lang.github.io/linter/lints/sort_constructors_first.html).
> > > So for eg :- Before it was
> > > ```
> > > class CollaboratorAttributes {
> > >     CollaboratorAttributes({
> > >     this.name,
> > >   });
> > > 
> > > String name;
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > and Now
> > > ```
> > > class CollaboratorAttributes {
> > >   String name;
> > >   CollaboratorAttributes({
> > >     this.name,
> > >   });
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Im new to this so i dont know i did the right thing or not.
> > > and yeah it was mentioned in those 26 issue so i started working on this without asking I didn't knew it was disabled.
> > 
> > 
> > Remove the rule from `analysis_options.yaml`.
> > This https://dart-lang.github.io/linter/lints/sort_constructors_first.html says GOOD as constructor being ordered at first and BAD if constructor is not in first. Your change does exactly the opposite.
> 
> So should i close this PR ?

If you can fix this rule, then you can make further changes to resolve the issues in this PR otherwise you can close it.

**Comment by M-A-D-A-R-A** [comment]
> > > > > @M-A-D-A-R-A Please explain your changes done in this PR along with how it fixes the rule (`sort_constructors_first`). Also I don't see this rule being enabled or removed from https://github.com/CircuitVerse/mobile-app/blob/master/analysis_options.yaml#L9
> > > > 
> > > > 
> > > > I refered to [this](https://dart-lang.github.io/linter/lints/sort_constructors_first.html).
> > > > So for eg :- Before it was
> > > > ```
> > > > class CollaboratorAttributes {
> > > >     CollaboratorAttributes({
> > > >     this.name,
> > > >   });
> > > > 
> > > > String name;
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > and Now
> > > > ```
> > > > class CollaboratorAttributes {
> > > >   String name;
> > > >   CollaboratorAttributes({
> > > >     this.name,
> > > >   });
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Im new to this so i dont know i did the right thing or not.
> > > > and yeah it was mentioned in those 26 issue so i started working on this without asking I didn't knew it was disabled.
> > > 
> > > 
> > > Remove the rule from `analysis_options.yaml`.
> > > This https://dart-lang.github.io/linter/lints/sort_constructors_first.html says GOOD as constructor being ordered at first and BAD if constructor is not in first. Your change does exactly the opposite.
> > 
> > 
> > So should i close this PR ?
> 
> If you can fix this rule, then you can make further changes to resolve the issues in this PR otherwise you can close it.

So like you said it was already in good state I think i shoul close this PR.

**Comment by manjotsidhu** [comment]
> > > > > > @M-A-D-A-R-A Please explain your changes done in this PR along with how it fixes the rule (`sort_constructors_first`). Also I don't see this rule being enabled or removed from https://github.com/CircuitVerse/mobile-app/blob/master/analysis_options.yaml#L9
> > > > > 
> > > > > 
> > > > > I refered to [this](https://dart-lang.github.io/linter/lints/sort_constructors_first.html).
> > > > > So for eg :- Before it was
> > > > > ```
> > > > > class CollaboratorAttributes {
> > > > >     CollaboratorAttributes({
> > > > >     this.name,
> > > > >   });
> > > > > 
> > > > > String name;
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > and Now
> > > > > ```
> > > > > class CollaboratorAttributes {
> > > > >   String name;
> > > > >   CollaboratorAttributes({
> > > > >     this.name,
> > > > >   });
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > Im new to this so i dont know i did the right thing or not.
> > > > > and yeah it was mentioned in those 26 issue so i started working on this without asking I didn't knew it was disabled.
> > > > 
> > > > 
> > > > Remove the rule from `analysis_options.yaml`.
> > > > This https://dart-lang.github.io/linter/lints/sort_constructors_first.html says GOOD as constructor being ordered at first and BAD if constructor is not in first. Your change does exactly the opposite.
> > > 
> > > 
> > > So should i close this PR ?
> > 
> > 
> > If you can fix this rule, then you can make further changes to resolve the issues in this PR otherwise you can close it.
> 
> So like you said it was already in good state I think i shoul close this PR.

Please note that the rule is still disabled, our aim is to enable the rule and make the changes if we are not following them so that Flutter Analyzer doesn't throw errors/warnings.

**Comment by M-A-D-A-R-A** [comment]
> > > > > > > @M-A-D-A-R-A Please explain your changes done in this PR along with how it fixes the rule (`sort_constructors_first`). Also I don't see this rule being enabled or removed from https://github.com/CircuitVerse/mobile-app/blob/master/analysis_options.yaml#L9
> > > > > > 
> > > > > > 
> > > > > > I refered to [this](https://dart-lang.github.io/linter/lints/sort_constructors_first.html).
> > > > > > So for eg :- Before it was
> > > > > > ```
> > > > > > class CollaboratorAttributes {
> > > > > >     CollaboratorAttributes({
> > > > > >     this.name,
> > > > > >   });
> > > > > > 
> > > > > > String name;
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > and Now
> > > > > > ```
> > > > > > class CollaboratorAttributes {
> > > > > >   String name;
> > > > > >   CollaboratorAttributes({
> > > > > >     this.name,
> > > > > >   });
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > Im new to this so i dont know i did the right thing or not.
> > > > > > and yeah it was mentioned in those 26 issue so i started working on this without asking I didn't knew it was disabled.
> > > > > 
> > > > > 
> > > > > Remove the rule from `analysis_options.yaml`.
> > > > > This https://dart-lang.github.io/linter/lints/sort_constructors_first.html says GOOD as constructor being ordered at first and BAD if constructor is not in first. Your change does exactly the opposite.
> > > > 
> > > > 
> > > > So should i close this PR ?
> > > 
> > > 
> > > If you can fix this rule, then you can make further changes to resolve the issues in this PR otherwise you can close it.
> > 
> > 
> > So like you said it was already in good state I think i shoul close this PR.
> 
> Please note that the rule is still disabled, our aim is to enable the rule and make the changes if we are not following them so that Flutter Analyzer doesn't throw errors/warnings.

So should i Enable this this rule?

**Comment by manjotsidhu** [comment]
> > > > > > > > @M-A-D-A-R-A Please explain your changes done in this PR along with how it fixes the rule (`sort_constructors_first`). Also I don't see this rule being enabled or removed from https://github.com/CircuitVerse/mobile-app/blob/master/analysis_options.yaml#L9
> > > > > > > 
> > > > > > > 
> > > > > > > I refered to [this](https://dart-lang.github.io/linter/lints/sort_constructors_first.html).
> > > > > > > So for eg :- Before it was
> > > > > > > ```
> > > > > > > class CollaboratorAttributes {
> > > > > > >     CollaboratorAttributes({
> > > > > > >     this.name,
> > > > > > >   });
> > > > > > > 
> > > > > > > String name;
> > > > > > > ```
> > > > > > > 
> > > > > > > 
> > > > > > >     
> > > > > > >       
> > > > > > >     
> > > > > > > 
> > > > > > >       
> > > > > > >     
> > > > > > > 
> > > > > > >     
> > > > > > >   
> > > > > > > and Now
> > > > > > > ```
> > > > > > > class CollaboratorAttributes {
> > > > > > >   String name;
> > > > > > >   CollaboratorAttributes({
> > > > > > >     this.name,
> > > > > > >   });
> > > > > > > ```
> > > > > > > 
> > > > > > > 
> > > > > > >     
> > > > > > >       
> > > > > > >     
> > > > > > > 
> > > > > > >       
> > > > > > >     
> > > > > > > 
> > > > > > >     
> > > > > > >   
> > > > > > > Im new to this so i dont know i did the right thing or not.
> > > > > > > and yeah it was mentioned in those 26 issue so i started working on this without asking I didn't knew it was disabled.
> > > > > > 
> > > > > > 
> > > > > > Remove the rule from `analysis_options.yaml`.
> > > > > > This https://dart-lang.github.io/linter/lints/sort_constructors_first.html says GOOD as constructor being ordered at first and BAD if constructor is not in first. Your change does exactly the opposite.
> > > > > 
> > > > > 
> > > > > So should i close this PR ?
> > > > 
> > > > 
> > > > If you can fix this rule, then you can make further changes to resolve the issues in this PR otherwise you can close it.
> > > 
> > > 
> > > So like you said it was already in good state I think i shoul close this PR.
> > 
> > 
> > Please note that the rule is still disabled, our aim is to enable the rule and make the changes if we are not following them so that Flutter Analyzer doesn't throw errors/warnings.
> 
> So should i Enable this this rule, and then work on this ?

Yep

**Pull request closed without merging**
