### PR TITLE
Migrate to null safety 

### LINKED ISSUE #99: Dart: Migrate to null safety
**Describe the bug**
We should be migrating to null safety which was introduced in Dart 2.0. But before that, we need to make sure that first our dependencies are migrated to null safety according to this Guide: https://dart.dev/null-safety/migration-guide

```
Wait for the packages that you depend on to migrate.
Migrate your package’s code, preferably using the interactive migration tool.
Statically analyze your package’s code.
Test to make sure your changes work.
If the package is already on pub.dev, publish the null-safe version as a prerelease version.
```

This Issue serves as a checklist of all the packages which have been migrated to null safety. 

- [x] animations
- [x] cupertino_icons
- [x] datetime_picker_formfield
- [x] flutter_facebook_auth
- [x] flutter_html
- [x] #119
- [x] flutter_keyboard_visibility
- [x] flutter_summernote (published on 21st June)
- [x] flutter_svg
- [x] flutter_typeahead
- [x] get
- [x] get_it
- [x] google_sign_in
- [x] html
- [x] http
- [x] intl
- [x] mockito
- [x] oauth2_client
- [x] photo_view
- [x] provider
- [x] share
- [x] shared_preferences
- [x] theme_provider
- [x] timeago
- [x] transparent_image
- [x] url_launcher

Once this list is complete which means all our packages are sound null safety. We should use migration tool to migrate to null safety.

### PR DESCRIPTION
**Pull request by aman-singh7**
Fixes #99 

Describe the changes you have made in this PR -

Screenshots of the changes (If any) -

Note: Please check Allow edits from maintainers. if you would like us to assist in the PR.

### CODE REVIEW

**Comment by manjotsidhu** [comment]
@aman-singh7 in CI/CD build step you can remove `--no-sound-null-safety`

https://github.com/CircuitVerse/mobile-app/blob/master/.github/workflows/ci.yml#L32

**Comment by aman-singh7** [comment]
@manjotsidhu migration is done. I am currently refactoring the test. Could you test the app when available and do let me know any issues?

**Comment by manjotsidhu** [comment]
@aman-singh7 the changes are working fine. Will review the code soon.

**Comment by manjotsidhu** [comment]
@aman-singh7 I will update the pods soon

**Review by manjotsidhu — APPROVED** [review]
YesSirSaluteGIF

**Review by Nitish145 — APPROVED** [review]
Thanks @aman-singh7 for your valuable contributions here.

**Pull request merged**
