### PR TITLE
About CV: Enable JavaScript for webview (Fixes #18).

### LINKED ISSUE #18: Search button and hamburger menu not working in the webview of Terms of Service and Privacy policy screens
**Is your feature request related to a problem? Please describe.**
The search functionality and hamburger menu are not working in the webview of Terms of service and Privacy Policy screen. Nothing happens on tap of search button and hamburger menu.

image

**Are you working on this? (Yes/No)**
No

### PR DESCRIPTION
**Pull request by manjotsidhu**
This Pull Request enables JavaScript while rendering URLs in `flutter_webview`. This fixes issue #18 in which JS specific components like hamburger menu and search were not working.

### CODE REVIEW

**Comment by tachyons** [comment]
Search should be using search api endpoint and native view instead of the
web view.

**Comment by manjotsidhu** [comment]
@tachyons You mean the links should open outside the app in native browser ?

**Comment by Nitish145** [comment]
Adding to what @tachyons said, this whole page/view needs to be written natively and not just a web view.

Search and related stuff may then be done natively.

**Comment by manjotsidhu** [comment]
@Nitish145 Thanks for helping, this is my day 1 of exploring mobile-app. I would require some time to do that. Also I have seen many pages loading from WebView instead of being natively written, Is there any roadmap as such to begin with ?

Also should I close this PR ? since we are now focusing on future implementation of all the WebView pages.

**Comment by Nitish145** [comment]
@manjotsidhu the privacy policy and the terms and conditions needs to be written natively AFAIR.

And yes this PR can be closed.

**Pull request closed without merging**
