### PR TITLE
Fix CI pipeline

### PR DESCRIPTION
**Pull request by Tanmoy741127**
**Fixes -**
- many textstyle has been deprecated after v3.1.0-0.0.pre
- flutter format has been deprecated

**Describe the changes you have made in this PR -**
- In codebase deprecated TextStyle has been updated as per this docs : https://api.flutter.dev/flutter/material/TextTheme-class.html
- in ci.yml `flutter format` has been 

Note: Please check Allow edits from maintainers. if you would like us to assist in the PR.

### CODE REVIEW

**Review by tachyons — APPROVED** [review]

**Comment by Tanmoy741127** [comment]
@aman-singh7 @manjotsidhu can you take a look to this .
The CI pipeline is broken.
The CI is failing at `flutter pub get` for `windows-latest`.

**Comment by Tanmoy741127** [comment]
@manjotsidhu i have not changed the setps actually. Will try to add that specific line. 
Thanks

**Comment by Tanmoy741127** [comment]
@manjotsidhu can you run the workflow once of this PR. Last time ot was going fine for ubuntu and windows. mac needs some more time, so increased timeout by 5 minute

**Comment by Tanmoy741127** [comment]
@manjotsidhu @tachyons now ig it's ready to be merged . As , the deprecation warning and CI has been resolved.

**Review by manjotsidhu — APPROVED** [review]

**Pull request merged**
