### PR TITLE
Added pinch to zoom and panning for circuit image in project detail page

### LINKED ISSUE #56: Add pinch to zoom in all the circuit image. Some images are very small and viewing the text is difficult without zooming it.
**Is your feature request related to a problem? Please describe.**
The circuit displayed in the project detail page is very small and there is no option to zoom.

**Describe the solution you'd like**
Add a full screen icon with the image that redirects the user to another page with the full screen of the image, this view would allow pinch to zoom so that the user can easily zoom and view the entire circuit

**Describe alternatives you've considered**
Alternatively, I could add a pinch to zoom in the existing page that allows to expand the image.

**Additional context**
Simulator Screen Shot - iPhone 11 Pro Max - 2021-01-16 at 00 16 59

**Are you working on this? (Yes/No)**
Yes

### PR DESCRIPTION
**Pull request by pratikbaid3**
Fixes #56 

Describe the changes you have made in this PR -
Added zoomable image and added two icons zoom in and zoom out. Pressing the zoom icon shows full screen circuit which can be pinched to zoom and panned

### CODE REVIEW

**Comment by pratikbaid3** [comment]
@manjotsidhu @Nitish145 please review. Thanks

**Comment by manjotsidhu** [comment]
I think this kind of pinch zoom effect will be better : https://medium.com/flutterdevs/pinch-zoom-effect-in-flutter-b16099a538e5

**Comment by pratikbaid3** [comment]
@manjotsidhu actually both provide the same effect. Using pinch_zoom_image_updated: ^0.2.6 dosen't allow us to use the FadeInImage.memoryNetwork widget and we will have to use Image.network instead which dosen't have the fade effect by default.

**Comment by pratikbaid3** [comment]
@manjotsidhu also pinch_zoom_image_updated: ^0.2.6 dosen't seem to be supported any more. There are several dependancy issue while importing 
[!] No podspec found for `pinch_zoom_image_updated` in `.symlinks/plugins/pinch_zoom_image_updated/ios`

**Comment by manjotsidhu** [comment]
Ok library doesn't matter, I was talking about the implementation. Instead of first tapping the zoom button, we should be able to zoom directly on it.

**Comment by pratikbaid3** [comment]
Oh ok got it. I'll implement that.

**Comment by pratikbaid3** [comment]
Untitled

**Comment by pratikbaid3** [comment]
@manjotsidhu I have made some changes. Please review.

**Comment by manjotsidhu** [comment]
@jaggu21 what you think is better ? the newly implemented one or this one: https://miro.medium.com/max/875/1*wU442EfvB8z2qg6gvvgI4Q.gif

**Comment by Nitish145** [comment]
> Untitled
> 

This looks good

**Comment by jaggu21** [comment]
> @jaggu21 what you think is better ? the newly implemented one or this one: https://miro.medium.com/max/875/1*wU442EfvB8z2qg6gvvgI4Q.gif
> 

I agree with @Nitish145 .

**Review by manjotsidhu — APPROVED** [review]

**Review by Nitish145 — APPROVED** [review]

**Pull request merged**
