### PR TITLE
bfix(drawer): name is not updating in drawer

### LINKED ISSUE #33: Profile Name change is not reflected on App Drawer
### Issue
After changing Profile Name, the new name is not reflecting in App Drawer and it will show new name only after restarting the App.

### Steps to reproduce this issue -
1. Go to Profile > Edit Profile > Change Name.
2. Check App Drawer, it should be reflecting the old name.
3. Restart the App and it will show the newly changed name.

Are you working on this? **No**

### PR DESCRIPTION
**Pull request by aman-singh7**
Fixes #33 

Describe the changes you have made in this PR - Initially, changes in profile are not reflected in the drawer instantaneously. So, I have used RxSharedPreferences to get the stream of the value from the SharedPreferences. 

Screenshots of the changes (If any) -

https://user-images.githubusercontent.com/77198905/160240847-23c0fd9a-7ee7-4550-b9e5-7ded76af773f.mp4

Note: Please check Allow edits from maintainers. if you would like us to assist in the PR.

### CODE REVIEW

**Comment by aman-singh7** [comment]
@manjotsidhu could you please update the pods? IOS build is failing. :sweat_smile:

**Comment by aman-singh7** [comment]
@manjotsidhu have you reviewed it? 😅

**Comment by aman-singh7** [comment]
@manjotsidhu reminder.. :sweat_smile:

**Comment by manjotsidhu** [comment]
Can you please explain why you used rx_shared_preferences. Is this the only way to get this issue fixed ? Using library for fixing this seems overkill

**Comment by aman-singh7** [comment]
`rx_shared_preferences` is just a wrapper around the `shared_preferences` (uses it internally) to provide the stream of the stored data with minimalistic changes. 
We can also fix this issue by providing the user data at the top level using provider. And for a small thing, following this approach does not make much sense.

And I think this is not overkilling because we are not adding new packages, we are just upgrading its capabilities.

**Comment by aman-singh7** [comment]
fixed in PR #217

**Pull request closed without merging**
