### PR TITLE
[fix#269] Removed Load more button from featured circuits page

### LINKED ISSUE #269: Revamp the `Feature circuits page`
**Is your feature request related to a problem? Please describe.**
Make UI interaction smoother.
1. If the network speed little bit slow, the loading time of circuits in `Featured Circuits` page varies and feels like unresponsive. 
2. We need to press `Load more` button again and again .

| 1. Blank screen while loading | 2, Load more button |
| --- | --- |
|  |  |
| --- | --- |

**Describe the solution you'd like**
1. Show a loading spinner in screen while loading the circuits
2. Replace `Load More` button with Infinite Scrolling. As soon as the user come at end of list, next list will start loading.

**Are you working on this? (Yes/No)**
No

### PR DESCRIPTION
**Pull request by danger-ahead**
Fixes #269 

Describe the changes you have made in this PR -
- [x] Removed Load more button from featured circuits page
- [x] Added Loading animation while loading the circuits

Screenshots of the changes (If any) -

[simplescreenrecorder-2023-03-02_03.48.19.webm](https://user-images.githubusercontent.com/55531939/222278239-ceda0ed9-e63a-484e-82e1-d32a476d5b12.webm)

### CODE REVIEW

**Review by Tanmoy741127 — CHANGES_REQUESTED** [review]
Looks fine .
I think it's not formatted.
Kindly format the code by `dart format .`

**Comment by danger-ahead** [comment]
> Looks fine . I think it's not formatted. Kindly format the code by `dart format .`

Hey it's already formatted. Check the reason why the build failed.
There were multiple deprecation warnings. I will open an issue shortly for this and fix the warnings.

**Comment by Tanmoy741127** [comment]
@tachyons can you run the workflow again

**Comment by Tanmoy741127** [comment]
@danger-ahead please merge your code with latest commits in main branch. As the old code consists some deprecation that has been fixed in latest update

**Comment by danger-ahead** [comment]
> @danger-ahead please merge your code with latest commits in main branch. As the old code consists some deprecation that has been fixed in latest update

@Tanmoy741127 Pushed after merging with master. Have a look!

**Comment by Tanmoy741127** [comment]
@vedant-jain03 @tachyons can you run the workflow

**Review by Tanmoy741127 — APPROVED** [review]
Good to go

**Review by vedant-jain03 — APPROVED** [review]
cc @manjotsidhu @aman-singh7

**Comment by manjotsidhu** [comment]
@danger-ahead Can we show loader when next set of circuits are being loaded ?

**Comment by manjotsidhu** [comment]
Also, please rebase your branch to pass CI checks

**Comment by danger-ahead** [comment]
[simplescreenrecorder-2023-03-05_07.55.19.webm](https://user-images.githubusercontent.com/55531939/222938279-abd7b1cd-962a-4542-8b45-e2f192117c1d.webm)

@vedant-jain03 @Tanmoy741127 @manjotsidhu 
Added loader while the next batch of circuits is being loaded. Have a look!

**Review by manjotsidhu — APPROVED** [review]
LGTM

**Pull request merged**
