### PR TITLE
fix: Timing spelling typo corrected

### LINKED ISSUE #86: Timing spelling is wrong in front page
**Describe the bug**
In the front page ,as the app opens the main screen after the logo, there is spelling mistake in timing. It is written "plot timimg diagrams" instead of "plot timing diagrams".
**To Reproduce**

1. Go to 'circuitverse app'
2. Scroll  to 'front page'
3. See error

**Expected behavior**
It should be written plot timing diagrams.

**Screenshots**

**Device Information [optional]:**

- OS: [Android]

**Additional context**

**Are you working on this issue? (Yes/No)**
No

### PR DESCRIPTION
**Pull request by suyash-patil**
Fixes #86 

Typo fixed in home_view.dart

### CODE REVIEW

**Comment by suyash-patil** [comment]
@manjotsidhu Please have a look at this.

**Review by manjotsidhu — APPROVED** [review]

**Comment by manjotsidhu** [comment]
The changes are fine but please change base branch to master.

**Comment by suyash-patil** [comment]
@manjotsidhu means should I make a new PR or just change the base branch

**Comment by manjotsidhu** [comment]
> @manjotsidhu means should I make a new PR or just change the base branch

Just change the base branch

**Comment by suyash-patil** [comment]
@manjotsidhu Done

**Review by Nitish145 — APPROVED** [review]

**Pull request merged**
