### PR TITLE
moved the theme changer slightly down

### LINKED ISSUE #244: The button to change themes must be a bit lower down on the sidebar
**Describe the bug**
The button to change the theme is a bit too close to the dynamic island on newer iPhone models. This makes clicking it a bit difficult. 

**To Reproduce**
Just open the sidebar from the homepage. 

**Expected behaviour**
The theme change icon should be a bit farther away from the dynamic island

**Screenshots**
image

**Device Information:**
iPhone 14 Pro Max

- OS: iOS 16.1

**Are you working on this issue? Yes**

### PR DESCRIPTION
**Pull request by anuragrao04**
Fixes #244 

Changes made in this PR - The theme changer button has been moved slightly down inorder to avoid hitting the dynamic island on newer iPhone models

Screenshots of the changes -
Refer the original issue for the before picture. After picture: 
Screenshot 2022-11-10 at 7 51 56 PM

### CODE REVIEW

**Comment by anuragrao04** [comment]
The changes are really small but this is my first PR to this repo and flutter in general!

**Comment by manjotsidhu** [comment]
@anuragrao04 Thanks for contributing, can you send a preview on Android with the above change ?

**Comment by aman-singh7** [comment]
Hey @anuragrao04, Instead of hardcoding, could you implement it with `SafeArea`. Wrap the Drawer child with SaferArea and test it on the devices.

**Comment by anuragrao04** [comment]
sure! I'll get it done as soon as possible

**Pull request closed without merging**
