### PR TITLE
Adding 'None' text to show when user has no groups

### PR DESCRIPTION
**Pull request by CoderMayhem**
Fixes #
Improving UX.

Describe the changes you have made in this PR -
Adding a text widget showing 'None' when the user is not a member of any group. Improves UX.

Screenshots of the changes (If any) -
Before :
before
After:
after

Note: Please check Allow edits from maintainers. if you would like us to assist in the PR.

### CODE REVIEW

**Comment by manjotsidhu** [comment]
Instead of "None", it would be better if we give a informative message. For example, For Groups You're in, "You are currently not in any groups, create or join a group to get started".

**Comment by CoderMayhem** [comment]
> Instead of "None", it would be better if we give a informative message. For example, For Groups You're in, "You are currently not in any groups, create or join a group to get started".

Won't it look a bit redundant and repetitive having the same message(you are currently not in any groups....) shown under both the **Groups You Mentor** and **Groups You're In** headings when we have given a **Make New Group** button just above it?

I guess we can remove the headings altogether and just display a single "You're not in any groups..." message in this case. Something like this :
group1
Let me know your thoughts.

**Comment by manjotsidhu** [comment]
> > Instead of "None", it would be better if we give a informative message. For example, For Groups You're in, "You are currently not in any groups, create or join a group to get started".
> 
> Won't it look a bit redundant and repetitive having the same message(you are currently not in any groups....) shown under both the **Groups You Mentor** and **Groups You're In** headings when we have given a **Make New Group** button just above it?
> 
> I guess we can remove the headings altogether and just display a single "You're not in any groups..." message in this case. Something like this :
> group1
> Let me know your thoughts.

I was just pointing out example for "Groups your In". I wanted your to decide the informative messages rather than just keeping just "None". Also, it's better to have both Mentored Groups and Joined Groups separate. It helps teachers/others to moderate.

**Comment by CoderMayhem** [comment]
Does this look fine??
group2

**Comment by Nitish145** [comment]
> Does this look fine??
> group2

Better! Also, get some views in the #ux channel.

**Comment by nitin10s** [comment]
It would be better if we could add a small illustration to this as well. also remove the grey bg, it looks odd

**Comment by RakeshSeervi** [comment]
we can show the two sections in a way we display projects created by the user and the ones starred by the user?

**Comment by manjotsidhu** [comment]
Since the PR is now stale and due to new changes, I am closing this PR. Feel free to open another one anytime :)
Thanks for Contributing 👍

**Pull request closed without merging**
