### PR TITLE
Disabled add button on empty input field of Add Collaborators form

### LINKED ISSUE #45: Disable add button on empty input field of Add Collaborators form
Implement same changes for Add Collaborators form as done in #32 .

### PR DESCRIPTION
**Pull request by ayan-biswas0412**
Fixes #45 

Describe the changes you have made in this PR -
I have changed the file ```lib/ui/views/projects/project_details_view.dart``` in line number 316 , integrated the disabling of add button on empty input field

I have taken help from this [PR](https://github.com/CircuitVerse/mobile-app/pull/32)

Screenshots of the changes (If any) -
image

Note: Please check Allow edits from maintainers. if you would like us to assist in the PR.

### CODE REVIEW

**Comment by cyber-venom003** [comment]
@ayan-biswas0412 I guess this has been solved in PR #32 itself.

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 I guess this has been solved in PR #32 itself.

1 have solved the problem of add collaborator form but In the PR #32 it was Add Group members section

**Comment by cyber-venom003** [comment]
@ayan-biswas0412 Please check the file changes I done in PR #32, the changes I implemented on the Add Group Members form, the same I done with Add Collaborators form.

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 Please check the file changes I done in PR #32, the changes I implemented on the Add Group Members form, the same I done with Add Collaborators form.

but the issue was open so I thought that it was missed in PR #32

**Comment by cyber-venom003** [comment]
No worries my friend @ayan-biswas0412 . It's my mistake that i forgot to close that issue 😅

**Comment by ayan-biswas0412** [comment]
> No worries my friend @ayan-biswas0412 . It's my mistake that i forgot to close that issue 😅

😅thank you no problem

**Pull request closed without merging**
