### PR TITLE
fixed issue where offline user was not able to see anything in featured circuits screen

### LINKED ISSUE #84: Missing Failed to load/ Error widget
**Describe the bug**
Should be a proper view if content failed to load due to some error like no internet or something

**To Reproduce**
Steps to reproduce the behaviour:
Turn off internet & load something.

**Screenshots**

**Device Information [optional]:**

- OS: Android

**Additional context**
No

**Are you working on this issue? (Yes/No)**
No

### PR DESCRIPTION
**Pull request by roopak99**
fixed issue where offline user was not able to see anything in featured circuits screen

Fixes #84 

Describe the changes you have made in this PR - i have added a condition to check if the model.FETCH_FEATURED_PROJECTS has an error and show that the user if offline if it is true

Screenshots of the changes (If any) - Screenshot

Note: Please check Allow edits from maintainers. if you would like us to assist in the PR.

### CODE REVIEW

**Comment by manjotsidhu** [comment]
@roopak99 thanks for contributing to CircuitVerse, we appreciate the effort. There are few points I would like to mention :
1. #84, focuses and requires Errors to be thrown in every page where ViewModel fetches content from API and not just for Featured Circuits.
2. The approach of this Issue requires errors for every kind of exceptions. Check `ApiUtils` for all possible exceptions.
3. Your implementation just checks if there is any error while fetching featured projects and throws "Looks like Offline" error to user irrespective of the nature of the error. There can be several types of errors that can be thrown and this is just a trivial case of offline. We would like to see errors for all types.
4. Typo "Looks like youre offline" -> "Looks like your offline".

**Comment by manjotsidhu** [comment]
If you are creative, try to reduce duplicate lines of code which implementing the functionality. 
**Hint**: Maybe you could try and have a CVException Widget which wraps any widget and throws errors for all exceptions. This widget then can be used in every page.

**Comment by roopak99** [comment]
Thanks for your valuable mentions. I will try my best to implement what you suggested.

**Comment by manjotsidhu** [comment]
Closing, PR being stale. Feel free to open another PR anytime.

**Pull request closed without merging**
